### ISSUE TITLE
Support for castlabs version naming

### ISSUE THREAD

**Issue by coredev-uk** [doyensec/electronegativity#110]
**Is your feature request related to a problem? Please describe.**
I understand you can manually set the electron version, however I am using the forge plugin which does not. I'm not sure if I should be here or reaching out to the forge devs.

**Describe the solution you'd like**
Basically just add an option to either specify a version schema or support for the `v<electronVersion>+wvcus` tag.

**Describe alternatives you've considered**
N/A

**Additional context**
See more at https://github.com/castlabs/electron-releases/releases

Thanks :)

**Comment by ikkisoft** [comment]
@coredev-uk We're no longer actively maintaining this project so I don't expect this to be implemented (unless we receive an external contribution).

**Comment by coredev-uk** [comment]
Okay, thanks for letting me know
