### ISSUE TITLE
BrowserWindow configs passed as variable is not supported

### ISSUE THREAD

**Issue by ikkisoft** [doyensec/electronegativity#32]
The current implementations of our JS checks do not support constructs in the following form:

```js
let moreInfoWindow;

let windowConfig = {
   width: 800,
   height: 600,
   webPreferences: {
       preload: path.join(__dirname, 'renderer.js'),
       sandbox: true,
       nodeIntegration: false,
   }
};

moreInfoWindow = new BrowserWindow(windowConfig);
moreInfoWindow.loadURL("https://www.doyensec.com/whatever");
```

All JS checks based on **webPreferences** are looking for the _BrowserWindow_ object astNode, and we don't have a way (do we?) to explore the entire AST again and determine the values of the webPreferences settings.

**Comment by ikkisoft** [comment]
This affects the following checks:

- AUXCLICK_JS_CHECK
- BLINK_FEATURES_JS_CHECK
- CONTEXT_ISOLATION_JS_CHECK
- EXPERIMENTAL_FEATURES_JS_CHECK
- INSECURE_CONTENT_JS_CHECK
- NODE_INTEGRATION_JS_CHECK
- PRELOAD_JS_CHECK
- SANDBOX_JS_CHECK
- WEB_SECURITY_JS_CHECK

**Comment by phosphore** [comment]
How about using https://github.com/estools/escope to get the list of declared variables in the global or function scope? It works natively with Esprima

**Comment by ikkisoft** [comment]
Seems like a good solution. We still need to modify the check's interface to pass the full _ast_ as argument, but then it's probably fairly easy to implement that. 

It won't work for TypeScript, but that's better than not having support at all.
