### ISSUE TITLE
Error when installing via npm on Ubuntu

### ISSUE THREAD

**Issue by bonkc** [doyensec/electronegativity#49]
**Describe the bug**
Installing via npm install @doyensec -g fails.

Linux <> 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
1.  sudo npm install @doyensec/electronegativity -g

**Expected behavior**
Install the app.

**Stacktraces **
npm ERR! path /usr/lib/node_modules/@doyensec/electronegativity/dist/index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/@doyensec/electronegativity/dist/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:

**Platform (please complete the following information):**
 - OS: Ubuntu
 - Latest via NPM

**Comment by olmomlo** [comment]
Same issue with following OS:

- Ubuntu 18.04.2 LTS
- Windows 10

Tested with 2 combinations: Node 12.1.0 + npm 6.9.0 & node 10.15.3 + npm 6.4.1

Thaks

**Comment by ikkisoft** [comment]
Thanks for the reports. We will fix this issue during the next week, and release a new update on NPM.

**Comment by phosphore** [comment]
We issued a new version bump ([v1.2.1](https://npmjs.com/package/@doyensec/electronegativity)) in order to fix this.
