### ISSUE TITLE
UnhandledPromiseRejectionWarning while fetching new Electron releases

### ISSUE THREAD

**Issue by Derek20** [doyensec/electronegativity#53]
**Describe the bug**
During a scan of my app, I receive a UnhandledPromiseRejectionWarning while the new Electron releases are being fetched.

**To Reproduce**
1. Run `electronegativity -i my-app`

**Expected behavior**
I expect the new Electron releases to be fetched and my app to be scanned.

**Stacktraces**

> Scan Status:
40 check(s) successfully loaded: 5 global, 35 atomic
████████████████████████████████████████ 100% | 9/9
Fetching Electron's new releases, this may take a while...

`(node:112) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'releases./"430ea9483d96f2286b350f4be5c9d5450ba9a5b3.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at AvailableSecurityFixesGlobalCheck.updateReleasesList (/usr/local/lib/node_modules/@doyensec/electronegativity/dist/finder/checks/GlobalChecks/AvailableSecurityFixesGlobalCheck.js:245:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04 LTS running under Windows 10 Linux subsystem
 - Electronegativity version: 1.3.0
- Electron version: 5.0.6

**Comment by phosphore** [comment]
Can't reproduce with:
- OS: Ubuntu 18.04.2 LTS
- Node: v8.10.0 or v12.5.0
- Electronegativity: v1.3.0 (i.e. https://github.com/doyensec/electronegativity/commit/eac6cfda78a95ae78455695b177c54501292f531)

Can you try removing the `releases.$etag.json` file on the project root and see if that solves you problem? From the error message you attached it seems that the filename for the releases file is wrong (`Error: ENOENT: no such file or directory, open 'releases./"430ea9483d96f2286b350f4be5c9d5450ba9a5b3.json'`).

**Comment by Derek20** [comment]
I tried removing the `releases.$etag.json` file and cloning the project again but still receiving the same error.

The release file in the project is `releases.cdb5eae279bd32c47a72ac526edf69d44385c732.json`
Whereas it is looking for `releases.430ea9483d96f2286b350f4be5c9d5450ba9a5b3.json`

Any ideas?
I'm running under the Windows Linux subsystem so perhaps something to do with that?

**Comment by phosphore** [comment]
I can't fathom why there should be a `/"` in the etag. Could you provide us the output of `curl -I https://raw.githubusercontent.com/electron/releases/master/index.json`?

**Comment by Derek20** [comment]
Here's the output you requested:

> HTTP/1.1 200 OK
> Content-Type: text/plain; charset=utf-8
> Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
> Strict-Transport-Security: max-age=31536000
> X-Content-Type-Options: nosniff
> X-Frame-Options: deny
> X-XSS-Protection: 1; mode=block
> ETag: "430ea9483d96f2286b350f4be5c9d5450ba9a5b3"
> Cache-Control: max-age=300
> X-Geo-Block-List:
> X-GitHub-Request-Id: B206:6626:64F13:92BE8:5D35B43C
> Accept-Ranges: bytes
> Content-Length: 28590121
> Accept-Ranges: bytes
> Date: Mon, 22 Jul 2019 13:03:57 GMT
> Via: 1.1 varnish
> Connection: keep-alive
> X-Served-By: cache-lcy19250-LCY
> X-Cache: MISS
> X-Cache-Hits: 0
> X-Timer: S1563800637.821994,VS0,VE657
> Vary: Authorization,Accept-Encoding, Accept-Encoding
> Access-Control-Allow-Origin: *
> X-Fastly-Request-ID: e5e3635f4f56951ed6497d858a16934fb695780d
> Expires: Mon, 22 Jul 2019 13:08:57 GMT
> Source-Age: 1

**Comment by phosphore** [comment]
@Derek20 I updated the global check to handle weak validators in etags (they starts with `'W/'`, so that was probably the culprit) in 0ed828733ac98d7a922e8995de0763f9b3643bbb. Try cloning the repo again and rebuilding it with `npm run build`.
Let me know if this fixes your problem.

**Comment by Derek20** [comment]
Thanks that's fixed it, the scan runs now!

FYI, it does say:

> Something went wrong while fetching Electron's releases. No connectivity?

**Comment by Derek20** [comment]
Nvm, the electron release list is now updated after running again.

**Comment by phosphore** [comment]
Great! Closing this for now.

**Comment by shivasurya** [comment]
When can we expect a release ? this will help us to implement it. @phosphore

**Comment by phosphore** [comment]
We'll probably release it as a minor version bump (v1.3.1) early next week. For now you can clone the repository and build it:
```
$ git clone https://github.com/doyensec/electronegativity.git
$ npm install .
$ npm run build
$ node dist/index.js -i inputFolder
```
