### ISSUE TITLE
Error when parsing app.js: "ImportDeclaration should appear when the mode is ES6 and in the module context."

### ISSUE THREAD

**Issue by vollkorn1982** [doyensec/electronegativity#56]
**Describe the bug**
When analysing an electron app I receive a parsing error message from eslint. Unfortunately this is an electron app I am not allowed to share.

**To Reproduce**
1. $ electronegativity -i .
```
▄▄▄ ▄▄▌ ▄▄▄ .▄▄·▄▄▄▄▄▄▄               
▀▄.▀██• ▀▄.▀▐█ ▌•██ ▀▄ █▪             
▐▀▀▪██▪ ▐▀▀▪██ ▄▄▐█.▐▀▀▄ ▄█▀▄         
▐█▄▄▐█▌▐▐█▄▄▐███▌▐█▌▐█•█▐█▌.▐▌        
 ▀▀▀.▀▀▀ ▀▀▀·▀▀▀ ▀▀▀.▀  ▀▀█▄▀▪        
 ▐ ▄▄▄▄ .▄▄ • ▄▄▄▄▄▄▄▪  ▌ ▐▪▄▄▄▄▄▄· ▄▌
•█▌▐▀▄.▀▐█ ▀ ▐█ ▀•██ ██▪█·██•██ ▐█▪██▌
▐█▐▐▐▀▀▪▄█ ▀█▄█▀▀█▐█.▐█▐█▐█▐█▐█.▐█▌▐█▪
██▐█▐█▄▄▐█▄▪▐▐█ ▪▐▐█▌▐█▌███▐█▐█▌·▐█▀·.
▀▀ █▪▀▀▀·▀▀▀▀ ▀  ▀▀▀▀▀▀. ▀ ▀▀▀▀▀  ▀ •
     v1.3.2  https://doyensec.com/

Scan Status:
40 check(s) successfully loaded: 5 global, 35 atomic
████████████████████████████████████████ 100% | 18/18
Error parsing <redacted>/resources/app/src/app.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
```

**Expected behavior**
Since the config file `/usr/lib/node_modules/@doyensec/electronegativity/.eslintrc.json` specifies the necessary options for parsing as a module:
```
    "parserOptions": {
        "ecmaVersion": 2017,
        "sourceType": "module"
    },
```
Therefore I would expect `app.js` to be parsed without problems.

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Electronegativity version: 1.3.2

**Comment by ikkisoft** [comment]
Thanks for the report. Is there any way that you could provide the code (or sanitized code) that trigger the error?

**Comment by vollkorn1982** [comment]
I reduced the code to a sample I can post here. The project folder is a single file `app.js`, which contains only the following line:
```
import { app, BrowserWindow, Menu, MenuItem, ipcMain, shell, dialog, remote } from 'electron';
```
This produces exactly the same error as above.

**Comment by vollkorn1982** [comment]
Hi, it's been a month and I want to introduce this tool to my colleagues early in November. Is there any way I can help with that?

I figured out that this is a problem with eslint and there seem to be several ways to fix this: https://github.com/eslint/eslint/issues/4344

* update eslint and babel-eslint as dependency for electronegativity
* add some config parameters in .eslintrc (but I don't know where to place this file for it to be used)

**Comment by ikkisoft** [comment]
Apologies for the delay, but unfortunately we still didn't find time to fix this issue. Rest assured - it's on our roadmap!

**Comment by ikkisoft** [comment]
Took a quick look in the past 5 minutes, but it's not just a simple dep upgrade. Updating eslint causes a new error ```Error: Cannot find module 'eslint/lib/util/traverser'``` due to a eslint's plugin (which I believe was removed in newer version).

**Comment by phosphore** [comment]
Hello @vollkorn1982 and thank you for your report,

Upgrading `eslint` was not enough to fix the issue, but we found that we did not extend the configuration of our AST parser to our scoping library (escope).

Let me know if you are still experiencing the problem after this fix.

**Comment by phosphore** [comment]
You will need to use `git clone` and then `npm install . &&  npm run build` for now.
We'll soon release a new version on npm with the fix for this issue.

**Comment by vollkorn1982** [comment]
Thanks a lot for the help. I managed to install and test the current master branch now and can confirm that this fixes the problem I described in this bug. Great tool!

**Comment by phosphore** [comment]
Glad to help. Let us know what your colleagues think of the tool! Electronegativity is always accepting new contributors or ideas :)
