### ISSUE TITLE
Better node module support

### ISSUE THREAD

**Issue by malept** [doyensec/electronegativity#59]
**Is your feature request related to a problem? Please describe.**

:wave: I'm one of the developers for Electron Forge, and I'd like to create a first-class Electron Forge plugin that would hook into the workflow right after an application is packaged (but before installers are generated). Currently, the `main` script for the module is the same as the bin, so when you `require('@doyensec/electronegativity')`, you'll just run the CLI without any arguments. This is sub-optimal for Electron Forge, as we'd have to shell out in order to configure it in any way.

**Describe the solution you'd like**

Move the `bin` script to a different file than `src/index.ts`, and export a Node API-friendly function instead.

If this sounds reasonable, I'd be happy to create a pull request for this.

**Comment by ikkisoft** [comment]
That's a great idea, and we would be welcome to support that change since it will bring security to many more Electron apps!

**Comment by malept** [comment]
FWIW, this helped a lot, I now have a PR for what I described: https://github.com/electron-userland/electron-forge/pull/1900
