### ISSUE TITLE
Different results between source files and asar package

### ISSUE THREAD

**Issue by bampakoa** [doyensec/electronegativity#61]
Hi,

I am trying to run your library against my Electron app and I have some issues:

1. Does it support Typescript files?
2. I run it twice, one with the actual source files and another with the asar package and I found some differences. When run with the source files it produced more results than the one with the asar package. In more detail, the results from the source files contained the real files with line numbers etc and the issues that were reported using the asar package.

Thanks

**Comment by phosphore** [comment]
Hey @bampakoa,

Thank you for your report. Electronegativity is currently does support typescript thanks to TypeScript ESTree. There shouldn't be differences between the asar package and the unpacked source, provided that the source files between the two are the same.
Maybe your asar is missing its `package.json`? Could you provide a reproducible code sample?

Thanks!

**Comment by bampakoa** [comment]
Hey @phosphore ,

I get back to this with some more information. My asar package contains a concatenated, minified and uglified version of the actual source files. Maybe this is going to be the source of the problem?

Overall I think that running the tool with the asar package does not seem to add some value. What do you think?

**Comment by phosphore** [comment]
> I get back to this with some more information. My asar package contains a concatenated, minified and uglified version of the actual source files. Maybe this is going to be the source of the problem?

Most probably yes. While it is certainly possible to run Electronegativity on packed production builds, it's not the original scope of this project. As a start, you could try checking if the `package.json` is included in the `app.asar` package.

> Overall I think that running the tool with the asar package does not seem to add some value. What do you think?
Again, this is just an additional feature for anyone who doesn't want to run `npx asar extract app.asar app` before launching the tool. Using the tool with the original sources is always desirable.
