### ISSUE TITLE
How to resolve issues with missing parsers? (eg, optionalChaining)

### ISSUE THREAD

**Issue by Slapbox** [doyensec/electronegativity#74]
**Is your feature request related to a problem? Please describe.**
Is it possible to use configure electronNegativity to use the necessary parsers? I can't find any information on that.

The exact message I get is: `This experimental syntax requires enabling the parser plugin: 'optionalChaining' `

I'm not sure how I'd go about configuring Electronegativity to understand this syntax. Am I overlooking something obvious?

**Comment by phosphore** [comment]
You may want to try to install the Babel's `optionalChaining` experimental plugin and add it to the Electronegativity's`.eslintrc.json` file. In Electronegativity, parsers are not that configurable per-se (I can only think about this `.eslintrc.json` file and maybe some options where they are instantiated), so I'm afraid that if the above doesn't work you'll need to actually edit Electronegativity's/Babel's plugin source to achieve that.

**Comment by Slapbox** [comment]
Thanks for your reply @phosphore!

That's an interesting idea that I'll look into. Did you mean the `.babelrc` file though? Or does Electronegativity's parsing somehow rely on `.eslintrc.json`?

**Comment by phosphore** [comment]
My bad, we use both Esprima and Babel, eslintrc is instead used for ESLintTraverser. Babel's plugins should be set in:
https://github.com/doyensec/electronegativity/blob/4db147d93d3d9b0d4a47a581b9a36e56883301bb/src/parser/parser.js#L29-L40

**Comment by Slapbox** [comment]
That's a huge help! Thanks so much!

I'll mark this as unread and when I get a chance to look into this further I'll report back.

**Comment by robotickamote** [comment]
Hi Guys, any news on this issue?

**Comment by bchurchill** [comment]
I'm thinking about adding a command line option to specify additional parser plugins.  That way plugins can be specified at run time, or by using the programmatic interface.

**Comment by phosphore** [comment]
Sorry about the delay merging this! Now 2d2cc9b5308d413d9bd014ba03cd57e9d8a229b3 is in [master](doyensec/electronegativity/tree/master)!

**Comment by paulrosania** [comment]
We're eager to adopt electronegativity – are you planning to release a version with this feature?

**Comment by phosphore** [comment]
I'll be working on the repository this incoming week and I'll release a new minor before EOW!

**Comment by paulrosania** [comment]
Amazing, thank you!!
