### ISSUE TITLE
Fails to install 1.8.1 on OSX

### ISSUE THREAD

**Issue by reZach** [doyensec/electronegativity#87]
**Describe the bug**
The package fails to install on OSX for version 1.8.1

**To Reproduce**
On OSX:
1. `git clone https://github.com/reZach/secure-electron-template.git`
2. `cd secure-electron-template`
3. Change package to version 1.8.1
4. `npm i`
5. [Error occurs](https://github.com/reZach/secure-electron-template/issues/56)

**Expected behavior**
I expect the package to install without error on OSX.

**Stacktraces **
```
WIN-HVPUU8BOK0U:test bivald$ npm install  @doyensec/electronegativity@1.8.1
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/xxxx/test/node_modules/@doyensec/electronegativity/dist/index.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/.../node_modules/@doyensec/electronegativity/dist/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Platform (please complete the following information):**
 - OS: Mac
 - Electronegativity version: 1.8.1

**Additional context**
I am the repository owner of the example in question, someone reported this error to me and I'm passing this to you to check if this _is_ a possible known issue to you and your team.

**Comment by ikkisoft** [comment]
`npm install  @doyensec/electronegativity@1.8.1` works on my testing machine. 

Also, the stacktrace includes the machine hostname `WIN-HVPUU8BOK0U` which suggest it's Windows !?

Closing until we get more details.

**Comment by reZach** [comment]
Thanks for your time @ikkisoft. I was able to test this on windows and mac and do not see any issue with this, please disregard (must have been something else!)

**Comment by reZach** [comment]
Re-opening @ikkisoft, the source OS is actually Linux. [Repro steps](https://github.com/reZach/secure-electron-template/issues/65#issue-810897795)

**Comment by reZach** [comment]
FYI @raphael10-collab

**Comment by phosphore** [comment]
Hello @reZach & @raphael10-collab,

I followed the [reproduction steps](https://github.com/reZach/secure-electron-template/issues/65#issue-810897795) on a Ubuntu 20.04.1 VM with node v10.19.0 && v14.5.0 and npm v6.14.4 and could install your template+electronegativity successfully.

I suggest @raphael10-collab to clone again the [reZach/secure-electron-template](https://github.com/reZach/secure-electron-template) and perform a fresh installation. Keep us posted!
