### ISSUE TITLE
Update Wiki Page about Context Isolation

### ISSUE THREAD

**Issue by vollkorn1982** [doyensec/electronegativity#90]
**Describe the bug**
https://github.com/doyensec/electronegativity/wiki/CONTEXT_ISOLATION_JS_CHECK says that context isolation is to be expected to be enabled by default in v5 of electron. This feature is enabled by default in v12 only, according to https://www.electronjs.org/docs/tutorial/context-isolation#how-do-i-enable-it

**To Reproduce**
1. Read https://github.com/doyensec/electronegativity/wiki/CONTEXT_ISOLATION_JS_CHECK
2. Compare with https://www.electronjs.org/docs/tutorial/context-isolation#how-do-i-enable-it

**Expected behavior**
I expect the information on the wiki pages to be accurate and not misleading.

**Stacktraces **
not applicable

**Platform (please complete the following information):**
github wiki pages

**Additional context**
not applicable

**Comment by phosphore** [comment]
Hello @vollkorn1982, thanks for noticing this!
The switch was actually planned for v5, so the docs reported an outdated prediction https://electronjs.org/docs/all#planned-breaking-api-changes-50. I updated the page to reflect the current state.
